#/run/numberOfThreads 4
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#/analysis/verbose 2
#/process/verbose 2
#/particle/verbose 2
#/process/setVerbose 2

#
#/process/inactivate msc
#/process/inactivate muIoni
#/process/inactivate CoulombScat
#/process/inactivate muonNuclear
#/process/inactivate muBrems
#/process/inactivate muPairProd

#
# muon to the direction (1.,0.,0.)
#
/gun/particle mu-
/gun/energy 10 GeV
#
#/run/printProgress 100
/run/beamOn 100
