/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/background white
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 1.5
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/set/globalLineWidthScale 2
/vis/viewer/set/defaultColour black
/vis/viewer/set/projection perspective

/vis/scene/endOfEventAction accumulate 500
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- red

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu-

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
