rule all_itk_performance_plots:
    input:
        expand("plots/itk-performance/default_single_mu_pt{pt}_eff_vs_eta.pdf", pt=[2, 10]),
        expand("plots/itk-performance/default_single_mu_pt{pt}_res_d0_vs_eta.pdf", pt=[2, 10]),
        "plots/itk-performance/default_ttbar_pu200_eff_vs_eta.pdf",
        "plots/itk-performance/default_ttbar_pu200_fake_vs_eta.pdf",

        expand("plots/itk-performance/default_mod_single_mu_pt{pt}_eff_vs_eta.pdf", pt=[2, 10]),
        expand("plots/itk-performance/default_mod_single_mu_pt{pt}_res_d0_vs_eta.pdf", pt=[2, 10]),
        "plots/itk-performance/default_mod_ttbar_pu200_eff_vs_eta.pdf",
        "plots/itk-performance/default_mod_ttbar_pu200_fake_vs_eta.pdf",

rule plot_itk_cmp_default_single_mu_eff_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_single_mu_pt{pt}/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_single_mu_pt{pt}/legacy/idpvm.root",
    output:
        "plots/itk-performance/default_single_mu_pt{pt}_eff_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} single_mu eff {input.idpvm_acts} {input.idpvm_legacy} --pt {wildcards.pt} --output {output}
        """

rule plot_itk_cmp_default_single_mu_res_d0_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_resolution_d0_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_single_mu_pt{pt}/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_single_mu_pt{pt}/legacy/idpvm.root",
    output:
        "plots/itk-performance/default_single_mu_pt{pt}_res_d0_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} single_mu {input.idpvm_acts} {input.idpvm_legacy} --pt {wildcards.pt} --output {output}
        """

rule plot_itk_cmp_default_ttbar_pu200_eff_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_ttbar_pu200/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_ttbar_pu200/legacy/idpvm.root",
    output:
        "plots/itk-performance/default_ttbar_pu200_eff_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} ttbar eff {input.idpvm_acts} {input.idpvm_legacy} --pu 200 --output {output}
        """

rule plot_itk_cmp_default_ttbar_pu200_fake_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_ttbar_pu200/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_ttbar_pu200/legacy/idpvm.root",
    output:
        "plots/itk-performance/default_ttbar_pu200_fake_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} ttbar fake {input.idpvm_acts} {input.idpvm_legacy} --pu 200 --output {output}
        """

rule plot_itk_cmp_default_mod_single_mu_eff_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_single_mu_pt{pt}/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_single_mu_pt{pt}/legacy/idpvm.root",
        idpvm_acts_mod = "data/itk-performance/default_single_mu_pt{pt}/acts_modified/idpvm.root",
    output:
        "plots/itk-performance/default_mod_single_mu_pt{pt}_eff_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} single_mu eff {input.idpvm_acts} {input.idpvm_legacy} --input-acts-mod {input.idpvm_acts_mod} --pt {wildcards.pt} --output {output}
        """

rule plot_itk_cmp_default_mod_single_mu_res_d0_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_resolution_d0_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_single_mu_pt{pt}/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_single_mu_pt{pt}/legacy/idpvm.root",
        idpvm_acts_mod = "data/itk-performance/default_single_mu_pt{pt}/acts_modified/idpvm.root",
    output:
        "plots/itk-performance/default_mod_single_mu_pt{pt}_res_d0_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} single_mu {input.idpvm_acts} {input.idpvm_legacy} --input-acts-mod {input.idpvm_acts_mod} --pt {wildcards.pt} --output {output}
        """

rule plot_itk_cmp_default_mod_ttbar_pu200_eff_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_ttbar_pu200/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_ttbar_pu200/legacy/idpvm.root",
        idpvm_acts_mod = "data/itk-performance/default_ttbar_pu200/acts_modified/idpvm.root",
    output:
        "plots/itk-performance/default_mod_ttbar_pu200_eff_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} ttbar eff {input.idpvm_acts} {input.idpvm_legacy} --input-acts-mod {input.idpvm_acts_mod} --pu 200 --output {output}
        """

rule plot_itk_cmp_default_mod_ttbar_pu200_fake_vs_eta:
    input:
        script = "scripts/itk-performance/plot_cmp_metric_vs_eta.py",
        idpvm_acts = "data/itk-performance/default_ttbar_pu200/acts/idpvm.root",
        idpvm_legacy = "data/itk-performance/default_ttbar_pu200/legacy/idpvm.root",
        idpvm_acts_mod = "data/itk-performance/default_ttbar_pu200/acts_modified/idpvm.root",
    output:
        "plots/itk-performance/default_mod_ttbar_pu200_fake_vs_eta.pdf",
    shell:
        """
        scripts/activate_and_run.sh python {input.script} ttbar fake {input.idpvm_acts} {input.idpvm_legacy} --input-acts-mod {input.idpvm_acts_mod} --pu 200 --output {output}
        """
