scan:
    number_of_events: 100

events:
    single_particles:
        number_of_events: 10
        events_per_slice: 10
        pts: [1, 10, 100]
        pt_range: [1, 100]
    ttbar:
        number_of_events: 1
        events_per_slice: 1
        pileup: 200

simulation:
    algorithms: ["fatras", "geant4"]

reconstruction:
    single_particles:
    ttbar:
        pileups: [0, 30, 60, 90, 120, 150, 200]
