name: Build

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: thesis
          root_file: thesis.tex
      - uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: thesis/thesis.pdf
